version: "3"
name: build
services:
  build:
    build:
      context: .
      dockerfile: dockerfile.build
    image: build
    container_name: app
    tty: true
    stdin_open: true
    volumes:
      - ./:/WWW/APP/
